apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: "letsencrypt-prod"
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "ops.aws@theresearch.group"
    privateKeySecretRef:
      name: letsencrypt-real
    solvers:
      - selector: {}
        dns01:
          route53:
            region: "ap-southeast-1"