apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-gateway
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/hungphaminnomizetech/test-argo-cd.git
      targetRevision: main
      ref: values
      helm:
        valueFiles:
          - $values/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-core
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
