apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: dev
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: rabbitmq
      targetRevision: 12.0.0 # You can update to the latest version
      helm:
        valueFiles:
          - $values/environments/dev/apps/core/rabbitmq/values.yaml
    - repoURL: https://github.com/hungphaminnomizetech/test-argo-cd.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-core
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
