auth:
  username: tra_albert_rabbitmq
  password: Albert_rabbit_01@

# auth:
#   username: tra_albert_rabbitmq
#   password: Albert_rabbit_01@

replicaCount: 1

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

# service:
#   type: ClusterIP

# replicaCount: 2

# clustering:
#   enabled: true
#   forceBoot: true

# resources:
#   limits:
#     cpu: 800m
#     memory: 1024Mi
#   requests:
#     cpu: 500m
#     memory: 512Mi

# livenessProbe:
#   enabled: true
#   initialDelaySeconds: 60
#   timeoutSeconds: 5
#   periodSeconds: 10
#   failureThreshold: 6

# readinessProbe:
#   enabled: true
#   initialDelaySeconds: 10
#   timeoutSeconds: 5
#   periodSeconds: 5
#   failureThreshold: 3

# extraConfiguration: |
#   loopback_users.guest = false
#   default_user_tags.administrator = true


service:
  type: ClusterIP